// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BigTextButton: typeof import('./src/components/BigTextButton.vue')['default']
    IconCarbonMoon: typeof import('~icons/carbon/moon')['default']
    IconCarbonSun: typeof import('~icons/carbon/sun')['default']
    IconClarityLanguageLine: typeof import('~icons/clarity/language-line')['default']
  }
}

export { }
